name: PrYv Admin Panel deployment workflow

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.4.1]

    steps:
      - name: Download master branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js with version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Login to the docker containers registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_PRYV_SERVER }}
          username: ${{ secrets.REGISTRY_PRYV_USERNAME }}
          password: ${{ secrets.REGISTRY_PRYV_PASSWORD }}

      - name: Get latest git tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
        id: get-latest-tag

      - name: Npm packages installation
        run: yarn install --frozen-lockfile # equivalent to "npm ci"

      - name: Tests
        run: yarn test

      - name: Build image
        run: cd ./build && docker build --rm -f Dockerfile -t ${{ secrets.REGISTRY_PRYV_SERVER }}/pryvio/app-web-admin:${{ steps.get-latest-tag.outputs.tag }} ./..

      - name: Upload new image to docker hub
        run: docker images && docker push ${{ secrets.REGISTRY_PRYV_SERVER }}/pryvio/app-web-admin:${{ steps.get-latest-tag.outputs.tag }}
